name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file SysProgWeb/Dockerfile --tag barankaynak/sistemprog2021:latest
    - name: Login Docker
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    - name: Publish
      run: docker push barankaynak/sistemprog2021:latest
